import type { BookSeries, Book, Chapter } from '../types';

export const SEED_SERIES: BookSeries[] = [
  {
    id: 'series-solo-monarch',
    name: 'Shadow Monarch: Level Up Beyond',
    title: 'Shadow Monarch: Level Up Beyond',
    slug: 'shadow-monarch-level-up-beyond',
    description: 'When the weakest E-rank hunter is left behind in a deadly double dungeon, a mysterious quest window appears before his eyes. Follow his journey as he unlocks the secrets of the Shadow Monarch and commands legions of the undead.',
    cover_image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'series-omniscient-apocalypse',
    name: 'Omniscient Reader in the Apocalypse',
    title: 'Omniscient Reader in the Apocalypse',
    slug: 'omniscient-reader-in-the-apocalypse',
    description: 'The fictional world of a three-thousand-chapter web novel suddenly becomes reality. As the only reader who finished the novel to the end, he knows how the world will end and how to survive the apocalyptic scenarios.',
    cover_image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-01-15T12:00:00.000Z',
  },
  {
    id: 'series-celestial-martial-god',
    name: 'Return of the Celestial Martial God',
    title: 'Return of the Celestial Martial God',
    slug: 'return-of-the-celestial-martial-god',
    description: 'Betrayed by his closest disciples and poisoned at the summit of Mount Hua, the Supreme Martial God awakens 300 years later in the body of a disgraced clan heir. Armed with divine heavenly techniques, he begins his reign anew.',
    cover_image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'series-villainess-destiny',
    name: 'The Villainess Reverses the Hourglass',
    title: 'The Villainess Reverses the Hourglass',
    slug: 'the-villainess-reverses-the-hourglass',
    description: 'Executed for sins she was framed for, she is given a second chance with a mystical golden hourglass that can turn back time. This time, she will play the game of nobility ruthlessly and claim her rightful throne.',
    cover_image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    status: 'COMPLETED',
    created_at: '2026-02-10T14:30:00.000Z',
  },
  {
    id: 'series-nano-emperor',
    name: 'Nano Machine Overlord',
    title: 'Nano Machine Overlord',
    slug: 'nano-machine-overlord',
    description: 'An illegitimate prince of the Demonic Cult is injected with high-tech nanomachines by a descendant from the distant future. The microscopic machines completely reconstruct his body, decipher ancient secret arts, and accelerate his martial mastery.',
    cover_image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-02-18T16:00:00.000Z',
  },
  {
    id: 'series-cyber-blade',
    name: 'Cyber Blade: Neo Tokyo 2099',
    title: 'Cyber Blade: Neo Tokyo 2099',
    slug: 'cyber-blade-neo-tokyo-2099',
    description: 'In the neon-drenched underbelly of Neo Tokyo, a cybernetically enhanced samurai assassin takes contracts from rogue AI factions while hunting the mega-corporation that wiped his memories.',
    cover_image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-03-01T11:00:00.000Z',
  },
  {
    id: 'series-tower-ascension',
    name: 'Tower of Infinite Ascension',
    title: 'Tower of Infinite Ascension',
    slug: 'tower-of-infinite-ascension',
    description: 'What do you desire? Money and wealth? Honor and pride? Authority and power? Revenge? Or something that transcends them all? Whatever you desire is at the top of the Tower.',
    cover_image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-03-05T09:00:00.000Z',
  },
  {
    id: 'series-blossoming-sword',
    name: 'Return of the Blossoming Sword Saint',
    title: 'Return of the Blossoming Sword Saint',
    slug: 'return-of-the-blossoming-sword-saint',
    description: 'The 13th disciple of the Great Mount Hua Sect, the Plum Blossom Sword Saint, defeated the Heavenly Demon and died atop the snowy mountain. He reincarnates a century later to find his beloved sect in complete ruins.',
    cover_image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    status: 'ONGOING',
    created_at: '2026-03-12T15:20:00.000Z',
  }
];

export const SEED_BOOKS: Book[] = SEED_SERIES.map((s, idx) => ({
  id: `book-${s.id}`,
  series_id: s.id,
  seriesId: s.id,
  title: `${s.title} - Season 1`,
  summary: s.description,
  description: s.description,
  cover_image: s.cover_image,
  coverUrl: s.cover_image,
  coin_price: idx % 2 === 1 ? 5 : 0,
  coinPrice: idx % 2 === 1 ? 5 : 0,
  pricing_model: idx % 2 === 1 ? 'PER_CHAPTER' : 'FREE',
  pricingModel: idx % 2 === 1 ? 'PER_CHAPTER' : 'FREE',
  default_chapter_coin_cost: idx % 2 === 1 ? 2 : 0,
  defaultChapterCoinCost: idx % 2 === 1 ? 2 : 0,
  status: 'PUBLISHED',
  category: idx % 3 === 0 ? 'Action' : idx % 3 === 1 ? 'Fantasy' : 'Romance',
  created_at: s.created_at,
}));

export const SEED_CHAPTERS: Chapter[] = SEED_BOOKS.flatMap((b) => {
  return [1, 2, 3, 4, 5, 6, 7, 8].map((num) => ({
    id: `chapter-${b.id}-${num}`,
    book_id: b.id,
    bookId: b.id,
    chapter_no: num,
    chapterNumber: num,
    title: `Chapter ${num}: ${num === 1 ? 'Prologue & The Awakening' : num === 2 ? 'The First Trial' : num === 3 ? 'Unexpected Encounter' : num === 4 ? 'Breakthrough' : num === 5 ? 'The Gathering Storm' : `Clash of Factions Part ${num - 5}`}`,
    sort_order: num * 10,
    sortOrder: num * 10,
    access_type: num > 3 && b.coin_price > 0 ? 'PAID' : 'FREE',
    pricing_model: num > 3 && b.coin_price > 0 ? 'PAID' : 'FREE',
    pricingModel: num > 3 && b.coin_price > 0 ? 'PAID' : 'FREE',
    coin_cost: num > 3 && b.coin_price > 0 ? 2 : 0,
    coinCost: num > 3 && b.coin_price > 0 ? 2 : 0,
    pdf_file_name: `${b.title.replace(/\s+/g, '_')}_Ch${num}.pdf`,
    pdfFileName: `${b.title.replace(/\s+/g, '_')}_Ch${num}.pdf`,
    pdf_page_count: 24,
    pdfPageCount: 24,
    content_status: 'READY',
    contentStatus: 'READY',
    published: true,
    created_at: new Date(Date.now() - (8 - num) * 86400000 * 3).toISOString(),
  }));
});
